routes/web.php
<?php

use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\GradeController;
use App\Http\Controllers\GradeSubjectController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TimeTableController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SessionController;
use App\Http\Controllers\SubjectController;
use App\Models\StudentAttendance;
use Illuminate\Support\Facades\Route;

require __DIR__ . '/auth.php';

Route::group(['prefix' => 'timetable', 'as' => 'timetable.'], function () {
    Route::get('/print', [TimeTableController::class, 'print'])->name('print');
    Route::post('/print', [TimeTableController::class, 'printFilter'])->name('print.filter');
    Route::get('/view', [TimeTableController::class, 'printView'])->name('print.view');
    Route::get('/', [TimeTableController::class, 'index'])->name('read.index');
    Route::post('/import', [TimeTableController::class, 'import'])->name('store.import');
    Route::get('/export', [TimeTableController::class, 'export'])->name('read.export');
    Route::post('/', [TimeTableController::class, 'store'])->name('submit.store');
    Route::get('/{timetable}/edit', [TimeTableController::class, 'edit'])->name('submit.edit');
    Route::put('/{timetable}/update', [TimeTableController::class, 'update'])->name('submit.update');
});

Route::group(['prefix' => 'public', 'as' => 'public.'], function () {
    Route::get('/allteachers/fingerprints', [TeacherController::class, 'allFingerprints'])->name('read.fingerprints');
    Route::get('/allstudents/fingerprints', [StudentController::class, 'allFingerprints'])->name('read.fingerprints');
});


Route::middleware(['auth'])->group(function () {

    Route::get('/', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::group(['prefix' => 'departments', 'as' => 'departments.'], function () {
        Route::group(['middleware' => 'admin'], function () {
            Route::get('/', [DepartmentController::class, 'index'])->name('read.index');
            Route::post('/', [DepartmentController::class, 'store'])->name('submit.store');
            Route::get('/{department}/edit', [DepartmentController::class, 'edit'])->name('submit.edit');
            Route::patch('/{department}/update', [DepartmentController::class, 'update'])->name('submit.update');
        });
        Route::get('/all/data', [DepartmentController::class, 'allData'])->name('read.data');
        Route::get('/{department}/class', [DepartmentController::class, 'departmentClasses'])->name('read.classes');
    });

    Route::group(['prefix' => 'grades', 'as' => 'grades.'], function () {
        Route::group(['middleware' => 'admin'], function () {
            Route::get('/', [GradeController::class, 'index'])->name('read.index');
            Route::post('/', [GradeController::class, 'store'])->name('submit.store');
            Route::get('/{grade}/edit', [GradeController::class, 'edit'])->name('submit.edit');
            Route::patch('/{grade}/update', [GradeController::class, 'update'])->name('submit.update');
            Route::get('/{grade}/students', [GradeController::class, 'students'])->name('read.students');
            Route::get('/attendance', [GradeController::class, 'gradesAttendacne'])->name('read.attendacne');
        });

        Route::get('/{grade}/subjects', [GradeController::class, 'subjects'])->name('read.subjects');
    });

    Route::group(['prefix' => 'subjects', 'as' => 'subjects.'], function () {
        Route::group(['middleware' => 'admin'], function () {
            Route::get('/', [SubjectController::class, 'index'])->name('read.index');
            Route::post('/', [SubjectController::class, 'store'])->name('submit.store');
            Route::get('/{subject}/edit', [SubjectController::class, 'edit'])->name('submit.edit');
            Route::patch('/{subject}/update', [SubjectController::class, 'update'])->name('submit.update');
            Route::get('/{subject}/teachers', [SubjectController::class, 'teachers'])->name('read.teachers');
        });
        Route::get('/all/data', [SubjectController::class, 'allData'])->name('read.data');
    });

    Route::group(['prefix' => 'sessions', 'as' => 'sessions.', 'middleware' => 'admin'], function () {
        Route::get('/', [SessionController::class, 'index'])->name('read.index');
        Route::post('/', [SessionController::class, 'store'])->name('submit.store');
        Route::get('/{session}/edit', [SessionController::class, 'edit'])->name('submit.edit');
        Route::patch('/{session}/update', [SessionController::class, 'update'])->name('submit.update');
    });

    Route::group(['prefix' => 'gradeSubjects', 'as' => 'gradeSubjects.', 'middleware' => 'admin'], function () {
        Route::get('/', [GradeSubjectController::class, 'index'])->name('read.index');
        Route::post('/', [GradeSubjectController::class, 'store'])->name('submit.store');
        Route::get('/{id}/edit', [GradeSubjectController::class, 'edit'])->name('submit.edit');
        Route::patch('/{id}/update', [GradeSubjectController::class, 'update'])->name('submit.update');
    });

    Route::group(['prefix' => 'students', 'as' => 'students.', 'middleware' => 'student'], function () {
        Route::get('/', [StudentController::class, 'index'])->name('read.index');
        Route::post('/', [StudentController::class, 'store'])->name('submit.store');
        Route::post('/manual-attendance', [StudentController::class, 'attendance'])->name('store.attendance');
        Route::post('/finalize-attendance', [StudentController::class, 'finalAttendance'])->name('store.finalAttendance');
        Route::get('/{student}/edit', [StudentController::class, 'edit'])->name('submit.edit');
        Route::put('/{student}/update', [StudentController::class, 'update'])->name('submit.update');
        Route::get('/promote', [StudentController::class, 'loadStudents'])->name('load.students');
        Route::post('/grade', [StudentController::class, 'showStudents'])->name('show.students');
        Route::get('/grade/{id}', [StudentController::class, 'gradeStudents'])->name('grade.students');
        Route::post('/gradeUpdate', [StudentController::class, 'updateStudentGrade'])->name('update.grade');
    });

    Route::group(['prefix' => 'admissions', 'as' => 'admissions.'], function () {
        Route::get('/', function () {
            return view('admission-form');
        })->name('read.index');
    });

    Route::group(['prefix' => 'teachers', 'as' => 'teachers.', 'middleware' => 'student'], function () {
        Route::get('/all/data', [TeacherController::class, 'allData'])->name('read.data');
        // Route::get('/all/fingerprints', [TeacherController::class, 'allFingerprints'])->name('read.fingerprints');
        Route::get('/', [TeacherController::class, 'index'])->name('read.index');
        Route::post('/', [TeacherController::class, 'store'])->name('submit.store');
        Route::get('/{teacher}/edit', [TeacherController::class, 'edit'])->name('submit.edit');
        Route::put('/{teacher}/update', [TeacherController::class, 'update'])->name('submit.update');
    });

    Route::group(['prefix' => 'newTeachers', 'as' => 'newTeachers.'], function () {
        Route::get('/', function () {
            return view('new-teacher');
        })->name('read.index');
    });

    Route::group(['prefix' => 'holidays', 'as' => 'holidays.', 'middleware' => 'admin'], function () {
        Route::get('/', function () {
            return view('holidays');
        })->name('read.index');
    });

    // Route::group(['prefix' => 'timetable', 'as' => 'timetable.', 'middleware' => 'timetable'], function () {
    //     Route::get('/print', [TimeTableController::class, 'print'])->name('print');
    //     Route::post('/print', [TimeTableController::class, 'printFilter'])->name('print.filter');
    //     Route::get('/view', [TimeTableController::class, 'printView'])->name('print.view');
    //     Route::get('/', [TimeTableController::class, 'index'])->name('read.index');
    //     Route::post('/import', [TimeTableController::class, 'import'])->name('store.import');
    //     Route::get('/export', [TimeTableController::class, 'export'])->name('read.export');
    //     Route::post('/', [TimeTableController::class, 'store'])->name('submit.store');
    //     // Route::get('/{timetable}/edit', [TimeTableController::class, 'edit'])->name('submit.edit')->middleware('timetableUdpate');
    //     // Route::put('/{timetable}/update', [TimeTableController::class, 'update'])->name('submit.update')->middleware('timetableUdpate');
    //     Route::get('/{timetable}/edit', [TimeTableController::class, 'edit'])->name('submit.edit');
    //     Route::put('/{timetable}/update', [TimeTableController::class, 'update'])->name('submit.update');
    // });

    Route::group(['middleware' => 'superAdmin'], function () {
        Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
            Route::get('/', [UserController::class, 'index'])->name('read.index');
            Route::post('/', [UserController::class, 'store'])->name('submit.store');
            Route::get('/{user}/edit', [UserController::class, 'edit'])->name('submit.edit');
            Route::patch('/{user}/update', [UserController::class, 'update'])->name('submit.update');
        });

        Route::group(['prefix' => 'roles', 'as' => 'roles.'], function () {
            Route::get('/all/data', [RoleController::class, 'allData'])->name('read.allData');
        });
    });

    Route::group(['prefix' => 'reports', 'as' => 'reports.', 'middleware' => 'reportAdmin'], function () {
        Route::get('/students', [StudentController::class, 'report'])->name('read.students');

resources/views/grades.blade.php
@extends('layouts.template')
@section('extra-css')
    <!-- Data Table CSS -->
    <link rel="stylesheet" href="{{ asset('assets/css/jquery.dataTables.min.css') }}">
    @livewireStyles
    @livewireScripts
@endsection
@section('content')
    <div class="dashboard-content-one">
    <!-- Breadcubs Area Start Here -->
    <div class="breadcrumbs-area">
        <h3>Classes</h3>
        <ul>
            <li><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li>Classes</li>
        </ul>
    </div>
    <!-- Breadcubs Area End Here -->
    <!-- Class Table Area Start Here -->
    <div class="row">
        <div class="col-4">
            <div class="card height-auto">
                <div class="card-body">
                    <div class="heading-layout1">
                        <div class="item-title">
                            <h3>Add New Class</h3>
                        </div>
                    </div>
                    @if (session()->has('status'))
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        {{ session('status') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif
                    <form class="new-added-form" action="{{ route('grades.submit.store') }}" method="post">
                        @csrf
                        @method('POST')
                        <div class="row">
                            <div class="col-12-xxxl col-lg-6 col-12 form-group">
                                <label>Name *</label>
                                <input type="text" placeholder="" class="form-control" name="name" id="name" value="{{ old('name') }}">
                                @error('name') <span class="text-red-500">{{ $message }}</span>@enderror
                            </div>
                            <div class="col-12-xxxl col-lg-6 col-12 form-group">
                                <label>Status *</label>
                                <select class="select2" name="status">
                                    <option value="">Please Select</option>
                                    <option value="1" {{ '1' == old("status", "") ? "selected" : "" }}>Active</option>
                                    <option value="0" {{ '0' == old("status", "") ? "selected" : "" }}>In-Active</option>
                                </select>
                                @error('status') <span class="text-red-500">{{ $message }}</span>@enderror
                            </div>
                            <div class="col-12 form-group mg-t-8">
                                <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
                                <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card height-auto">
                <div class="card-body">
                    <div class="heading-layout1">
                        <div class="item-title">
                            <h3>All Classes</h3>
                        </div>
                    </div>
                    <div class="table-responsive">
                        @if (session()->has('message'))
                            <div class="alert alert-primary" role="alert">
                                {{ session('message') }}
                            </div>
                        @endif

                        <table class="table display data-table text-nowrap">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($grades as $grade)
                                <tr>
                                    <td>{{ $grade->name ?? '' }}</td>
                                    <td>{{ ($grade->status ?? ''== 1) ? 'Active' : 'In-Active' }}</td>
                                    <td>
                                        <a href="{{ route('grades.submit.edit', $grade->id) }}" class="btn btn-primary btn-lg">Edit</a>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="4">No Class to Display</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Class Table Area End Here -->
@endsection
@section('extra-js')
    <!-- Data Table Js -->
    <script src="{{ asset('assets/js/jquery.dataTables.min.js') }}"></script>
@endsection

resources/views/slots.blade.php
@extends('layouts.template')
@section('extra-css')
    <!-- Data Table CSS -->
    <link rel="stylesheet" href="{{ asset('assets/css/jquery.dataTables.min.css') }}">
    @livewireStyles
    @livewireScripts
@endsection
@section('content')
    <div class="dashboard-content-one">
    <!-- Breadcubs Area Start Here -->
    <div class="breadcrumbs-area">
        <h3>Slots</h3>
        <ul>
            <li><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li>Slots</li>
        </ul>
    </div>
    <!-- Breadcubs Area End Here -->

    <!-- Class Table Area Start Here -->
    <div class="card height-auto">
        <div class="card-body">
            @livewire('slots')
        </div>
    </div>
    <!-- Class Table Area End Here -->
@endsection
@section('extra-js')
    <!-- Data Table Js -->
    <script src="{{ asset('assets/js/jquery.dataTables.min.js') }}"></script>
@endsection

resources/views/student-promotion.blade.php
@extends('layouts.template')
@section('extra-css')
<style>
    .select2-container {
        width: 100% !important;
    }
</style>
@endsection
@section('content')
    <div class="dashboard-content-one">
    <!-- Breadcubs Area Start Here -->
    <div class="breadcrumbs-area">
        <h3>Students</h3>
        <ul>
            <li><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li>Promote Students</li>
        </ul>
    </div>
    <!-- Breadcubs Area End Here -->

    <!-- Class Table Area Start Here -->
    <div class="row">
        <div class="col-12">
            <div class="card height-auto">
                <div class="card-body">
                    <div class="heading-layout1">
                        <div class="item-title">
                            <h3>Promote Student</h3>
                        </div>
                    </div>
                    <form class="new-added-form" method="post" action="{{ route('students.show.students') }}">
                        @csrf
                        <div class="row">
                            <div class="col-3 form-group">
                                <label>Department *</label>
                                <select class="select2" name="department_id" id="department_id" required>
                                    <option value="all">Select Departments</option>
                                    @foreach ($departments as $index => $department)
                                        <option value="{{ $department->id }}">{{ $department->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-3 form-group" required>
                                <label>Current Class *</label>
                                    <select name="current_grade" id="current_grade">
                                </select>
                            </div>
                            <div class="col-3 form-group" required>
                                <label>Promote To *</label>
                                    <select name="promote_to" id="promote_to">
                                </select>
                            </div>
                            <div class="col-3 form-group">
                                <label class="hidden-label">Submit</label>
                                <button type="submit"  class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Load Students</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    @if(isset($students) && !@empty($students))
    <div class="row">
        <div class="col-12">
            <div class="card height-auto">
                <div class="card-body">
                    <div class="heading-layout1">
                        <div class="item-title">
                            <h3>All Students</h3>
                        </div>
                    </div>
                    <div class="table-responsive">

                    <form class="new-added-form" method="post" action="{{ route('students.update.grade') }}">
                        @csrf
                        <input type="hidden" value="{{ $current_grade }}" name="current_grade" >
                        <input type="hidden" value="{{ $promote_to }}" name="promote_to" >
                        <table class="table display data-table text-nowrap">
                        {{-- <table id="students" class="display"> --}}
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>Sr</th>
                                    <th>Reg. No.</th>
                                    <th>Full Name</th>
                                    <th>Department</th>
                                    <th>Current Class</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                    $count = 1;
                                @endphp
                                @forelse ($students as $student)
                                <tr>
                                    <td><input type="checkbox" name="checked[]" value="{{ $student->registration_number }}" checked />&nbsp;</td>
                                    <td>{{ $count }}</td>
                                    <td>{{ $student->registration_number ?? '' }}</td>
                                    <td>{{ $student->full_name ?? '' }}</td>
                                    <td>{{ $student->department->name ?? '' }}</td>
                                    <td>{{ $student->grade->name ?? '' }}</td>
                                </tr>
                                @php
                                    $count++;
                                @endphp
                                @empty
                                <tr>
                                    <td colspan="4">No Student to Display</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                        <div class="col-4 form-group">
                            <button type="submit" class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Promote Students</button>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endif()
    <!-- Class Table Area End Here -->
@endsection
@section('extra-js')
<script>
    $(document).ready(function() {
        $('#current_grade').select2({
            placeholder: 'Current Class',
            ajax: {
                url: function() {
                    return "{{url('')}}"+"/departments/" + $("#department_id").val() + "/class";
                },
                dataType: 'json',
                processResults: function(data) {
                    // Transforms the top-level key of the response object from 'items' to 'results'
                    return {
                        results: data.items
                    };
                }
            }
        });
        $('#promote_to').select2({
            placeholder: 'Promote To',
            ajax: {
                url: function() {
                    return "{{url('')}}"+"/departments/" + $("#department_id").val() + "/class";
                },
                dataType: 'json',
                processResults: function(data) {
                    // Transforms the top-level key of the response object from 'items' to 'results'
                    return {
                        results: data.items
                    };
                }
            }
        });
    });
</script>
@endsection

resources/views/users.blade.php
@extends('layouts.template')
@section('extra-css')
    <!-- Data Table CSS -->
    <link rel="stylesheet" href="{{ asset('assets/css/jquery.dataTables.min.css') }}">
    <style>
        .select2-container {
            width: 100% !important;
        }

    </style>
    @livewireStyles
    @livewireScripts
@endsection
@section('content')
    <div class="dashboard-content-one">
        <!-- Breadcubs Area Start Here -->
        <div class="breadcrumbs-area">
            <h3>Users</h3>
            <ul>
                <li><a href="{{ route('dashboard') }}">Dashboard</a></li>
                <li>Users</li>
            </ul>
        </div>
        <!-- Breadcubs Area End Here -->

        <!-- Class Table Area Start Here -->
        <div class="row">
            <div class="col-4">
                <div class="card height-auto">
                    <div class="card-body">
                        <div class="heading-layout1">
                            <div class="item-title">
                                <h3>Add User</h3>
                            </div>
                        </div>
                        <form class="new-added-form" method="post" action="{{ route('users.submit.store') }}">
                            <div class="row">
                                @csrf
                                <div class="col-12 form-group">
                                    <label for="name">Full Name *</label>
                                    <input placeholder="Full Name" type="text" value="{{ old('name', '') }}"
                                        class="form-control" name="name" id="name">
                                    @error('name') <span class="text-red-500">{{ $message }}</span>@enderror
                                </div>
                                <div class="col-12 form-group">
                                    <label for="email">Email *</label>
                                    <input placeholder="Email" type="text" value="{{ old('email', '') }}"
                                        class="form-control" name="email" id="email">
                                    @error('email') <span class="text-red-500">{{ $message }}</span>@enderror
                                </div>
                                <div class="col-12 form-group">
                                    <label>Role *</label>
                                    <select name="role_id" id="role_id">
                                    </select>
                                    @error('role_id') <span class="text-red-500">{{ $message }}</span>@enderror
                                </div>
                                <div class="col-12 form-group">
                                    <label for="password">Password *</label>
                                    <input placeholder="Password" type="password" value="{{ old('password', '') }}"
                                        class="form-control" name="password" id="password">
                                    @error('password') <span class="text-red-500">{{ $message }}</span>@enderror
                                </div>
                                <div class="col-12 form-group">
                                    <label for="password">Password Confirmation*</label>
                                    <input placeholder="Password Confirmation" type="password"
                                        value="{{ old('password_confirmation', '') }}" class="form-control"
                                        name="password_confirmation" id="password_confirmation">
                                    @error('password_confirmation') <span
                                        class="text-red-500">{{ $message }}</span>@enderror
                                </div>
                                <div class="col-12 form-group mg-t-8">
                                    <button type="submit"
                                        class="btn-fill-lg btn-gradient-yellow btn-hover-bluedark">Save</button>
                                    <button type="reset" class="btn-fill-lg bg-blue-dark btn-hover-yellow">Reset</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-8">
                <div class="card height-auto">
                    <div class="card-body">
                        <div class="heading-layout1">
                            <div class="item-title">
                                <h3>All Users</h3>
                            </div>
                        </div>
                        <div class="table-responsive">
                            @if (session()->has('status'))
                                <div class="alert alert-primary alert-dismissible fade show" role="alert">
                                    {{ session('status') }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif

                            <table class="table display data-table text-nowrap">
                                <thead>
                                    <tr>
                                        <th>Full Name</th>
                                        <th>Email Address</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($users as $user)
                                        <tr>
                                            <td>{{ $user->name ?? '' }}</td>
                                            <td>{{ $user->email ?? '' }}</td>
                                            <td>
                                                <a class="btn btn-primary btn-lg"
                                                    href="{{ route('users.submit.edit', $user) }}">Edit</a>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="4">No User to Display</td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Class Table Area End Here -->
    @endsection
@section('extra-js')
    <!-- Data Table Js -->
    <script src="{{ asset('assets/js/jquery.dataTables.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $.ajax("{{ route('roles.read.allData') }}", {
                type: 'GET', // http method
                success: function(data, status, xhr) {
                    $('#role_id').select2({
                        placeholder: 'Select Role',
                        data: data.items
                    });
                },
                error: function(jqXhr, textStatus, errorMessage) {
                    $('#role_id').select2({
                        placeholder: 'Select Role',
                        data: []
                    });
                }
            });
        });
    </script>
@endsection